version: '3'
services:

  discovery-server:
    container_name: discovery-server
    build:
      context: discovery-server
      dockerfile: Dockerfile
    image: discovery-server:0.0.1-SNAPSHOT
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - emp-network
  User:
    container_name: User
    build:
      context: User
      dockerfile: Dockerfile
      args:
        dburl: 'jdbc:mysql://10.0.75.1:3306/user_db?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
        dbuser: 'root'
        dbpass: 'orion12345678'
        rabbithost: '10.0.75.1'
    image: user:0.0.1-SNAPSHOT
    entrypoint: /opt/User-entrypoint.sh
    expose:
      - 8081
    ports:
      - 8081:8081
    networks:
      - emp-network
    links:
      - discovery-server:discovery-server
    depends_on:
      - discovery-server
  BookDetails:
    container_name: BookDetails
    build:
      context: BookDetails
      dockerfile: Dockerfile
      args:
        dburl: 'jdbc:mysql://10.0.75.1:3306/book_details_db?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
        dbuser: 'root'
        dbpass: 'orion12345678'
        rabbithost: '10.0.75.1'
    image: book-details:0.0.1-SNAPSHOT
    entrypoint: /opt/BookDetails-entrypoint.sh
    expose:
      - 8082
    ports:
      - 8082:8082
    networks:
      - emp-network
    links:
      - discovery-server:discovery-server
    depends_on:
      - discovery-server
  Books:
    container_name: Books
    build:
      context: Books
      dockerfile: Dockerfile
      args:
        dburl: 'jdbc:mysql://10.0.75.1:3306/user_book_db?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
        dbuser: 'root'
        dbpass: 'orion12345678'
        rabbithost: '10.0.75.1'
    image: books:0.0.1-SNAPSHOT
    entrypoint: /opt/Books-entrypoint.sh
    expose:
      - 8083
    ports:
      - 8088:8083
    networks:
      - emp-network
    links:
      - discovery-server:discovery-server
    depends_on:
      - discovery-server
  netflix-zuul-api-gateway-server:
    container_name: netflix-zuul-api-gateway-server
    build:
      context: netflix-zuul-api-gateway-server
      dockerfile: Dockerfile
    image: api-gateway:0.0.1-SNAPSHOT
    entrypoint: /opt/Api-gateway-entrypoint.sh
    expose:
      - 8765
    ports:
      - 8765:8765
    networks:
      - emp-network
    links:
      - discovery-server:discovery-server
    depends_on:
      - discovery-server
networks:
  emp-network:
    driver: bridge